name: 'Deploy'
description: 'Deploy'

inputs:
  environment:
    required: true
    description: "Environment"
  ARTIFACT_TOKEN:
    required: true
    description: "Artifact token"

runs:
  using: "composite"
  steps:
    # Checkout project
    - uses: actions/checkout@v3
      with:
        path: main

    # Setup buildx
    # - name: "Buildx"
    #   shell: bash
    #   run: docker buildx create --use

    # Build dev
    - name: "Build development"
      if: ${{ inputs.environment == 'development' }}
      shell: bash
      run: |
        docker build \
        -t ${{ env.IMAGE_REF }} \
        --build-arg ARTIFACT_TOKEN=${{ inputs.ARTIFACT_TOKEN }} \
        --platform=linux/amd64 \
        --target=${{ env.DOCKER_BUILD_TARGET }} \
        main
        docker push ${{ env.IMAGE_REF }}

        docker tag ${{ env.IMAGE_REF }} ${{env.ACR_LOGIN_SERVER}}/${{env.IMAGE_NAME}}:beta
        docker push ${{env.ACR_LOGIN_SERVER}}/${{env.IMAGE_NAME}}:beta

    # Build staging
    - name: "Build staging"
      if: ${{ inputs.environment == 'staging' }}
      shell: bash
      run: |
        echo "Do nothing for the moment"
      # docker buildx build \
      # --cache-from=${{ env.IMAGE_REF }} \
      # --build-arg ARTIFACT_TOKEN=${{ inputs.ARTIFACT_TOKEN }} \
      # -t ${{ env.IMAGE_REF }}-staging \
      # --platform=linux/amd64 \
      # --target=${{ env.DOCKER_BUILD_TARGET }} \
      # --push main

    # Build production
    - name: "Build production"
      if: ${{ inputs.environment == 'production' }}
      shell: bash
      working-directory: main
      run: |
        docker pull ${{ env.IMAGE_REF }}

        defaultBranch=$(git remote show origin | sed -n '/HEAD branch/s/.*: //p')
        docker tag ${{ env.IMAGE_REF }} ${{env.ACR_LOGIN_SERVER}}/${{env.IMAGE_NAME}}:$defaultBranch
        docker push ${{env.ACR_LOGIN_SERVER}}/${{env.IMAGE_NAME}}:$defaultBranch
      # docker buildx build \
      # --cache-from=${{ env.IMAGE_REF }}-dev \
      # --build-arg ARTIFACT_TOKEN=${{ inputs.ARTIFACT_TOKEN }} \
      # -t ${{ env.IMAGE_REF }} \
      # --platform=linux/amd64 \
      # --target=${{ env.DOCKER_BUILD_TARGET }} \
      # --push main