#
# Build and publish image to ACR with semver tag
# Then, ask kubernetes-resources-v2 to deploy on development, staging or production
#

name: Build and deploy image with semver

on:
  workflow_call:
    inputs:
      imageName:
        description: 'An image name passed from the caller workflow'
        required: true
        type: string

      semverTagName:
        description: 'A tag name passed from the caller workflow'
        required: true
        type: string

      buildTarget:
        required: false
        type: string
        description: "Build target"
        default: prod

      kubernetesResourcesPath:
        required: false
        type: string
        default: .vik-app.image
        description: Custom kubernetes-resources-v2 image path to update

env:
  ACR_LOGIN_SERVER: wefight2.azurecr.io
  IMAGE_REF: ${{ env.ACR_LOGIN_SERVER }}/${{ inputs.imageName }}:${{ inputs.semverTagName }}

jobs:
  build-publish:
    name: Build and publish docker image to ACR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build development
        run: |
          docker build \
          -t ${{ env.IMAGE_REF }} \
          --build-arg ARTIFACT_TOKEN=${{ secrets.ARTIFACT_TOKEN }} \
          --build-arg PACKAGES_GITHUB_TOKEN=${{ secrets.PACKAGES_GITHUB_TOKEN }} \
          --build-arg AZURE_TOKEN=${{ secrets.AZURE_TOKEN }} \
          --platform=linux/amd64 \
          --target=${{ inputs.buildTarget }} \
          .

      - name: Publish
        run: docker push ${{ env.IMAGE_REF }}

  deploy-dev:
    needs: build-publish
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - environment: dev
          - environment: stage

    name: Deploy image to ${{ matrix.environment }}
    environment: ${{ matrix.environment }}

    steps:
      - name: 'Curl kubernetes-resources-v2'
        run: |
          curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/wefight-devs/kubernetes-resources-v2/actions/workflows/on_workflow_dispatch.yaml/dispatches -d '{"ref":"main","inputs":{"imageName":"${{ inputs.imageName }}","imageSemver":"${{ inputs.semverTagName }}", "environment": "${{ matrix.environment }}", "customPath": "${{ inputs.kubernetesResourcesPath }}"}}'

  deploy-prod:
    needs: deploy-dev
    runs-on: ubuntu-latest
    name: Deploy image to production
    environment: production

    steps:
      - name: 'Curl kubernetes-resources-v2'
        run: |
          curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/wefight-devs/kubernetes-resources-v2/actions/workflows/on_workflow_dispatch.yaml/dispatches -d '{"ref":"main","inputs":{"imageName":"${{ inputs.imageName }}","imageSemver":"${{ inputs.semverTagName }}", "environment": "prod-fr", "customPath": "${{ inputs.kubernetesResourcesPath }}"}}'

          curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/wefight-devs/kubernetes-resources-v2/actions/workflows/on_workflow_dispatch.yaml/dispatches -d '{"ref":"main","inputs":{"imageName":"${{ inputs.imageName }}","imageSemver":"${{ inputs.semverTagName }}", "environment": "prod-uae", "customPath": "${{ inputs.kubernetesResourcesPath }}"}}'
