name: Reusable semantic-release workflow

on:
  workflow_call:
    inputs:
      teamsGroup:
        required: true
        type: string
        description: Group for TEAMS notification

      dryRun:
        required: false
        default: false
        type: boolean
        description: Should run on dry-run mode

      cache:
        required: false
        type: string
        description: "NodeJS Cache: npm, yarn or pnpm)"

      shouldChmod777GenerateNotes:
        required: false
        type: boolean
        description: "Should chmod 777 generate_notes.sh"
        default: false

      workDir:
        description: 'The source root directory of the project'
        required: false
        type: string
        default: .

      currentBranch: # Set to `currentBranch: ${{ github.head_ref }}` in your commit check workflow for dry runs
        description: 'The principal branch of the project'
        required: false
        type: string
        default: main

jobs:
  run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.workDir }}
    env:
      PACKAGES_GITHUB_TOKEN: ${{ secrets.PACKAGES_GITHUB_TOKEN }}
      ARTIFACT_TOKEN: ${{ secrets.ARTIFACT_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.PACKAGES_GITHUB_TOKEN }}
      TEAMS_WEBHOOK_SECRET_KEY: ${{inputs.teamsGroup}}_TEAMS_WEBHOOK_URL
      HUSKY: 0

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: chmod generate_notes.sh
        if : ${{inputs.shouldChmod777GenerateNotes}}
        run: chmod 777 ./scripts/generate_notes.sh

      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: ${{ inputs.cache }}
          registry-url: 'https://npm.pkg.github.com'
          scope: '@wefight-devs'

      - name: npm install semantic-release
        run: |
          npm install semantic-release @semantic-release/exec @semantic-release/git @semantic-release/github @semantic-release/changelog semantic-release-ms-teams@^1.2.1

      # Generate semver
      - name: Semantic Release dry run
        if: inputs.dryRun == true
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets[env.TEAMS_WEBHOOK_SECRET_KEY] }}
        run: GITHUB_EVENT_NAME="push" GITHUB_REF=${{inputs.currentBranch}} npx semantic-release --dry-run --branches ${{inputs.currentBranch}}

      - name: Semantic Release
        if: inputs.dryRun == false
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets[env.TEAMS_WEBHOOK_SECRET_KEY] }}
        run: GITHUB_EVENT_NAME="push" npx semantic-release
