name: Reusable tests with docker-compose workflow

on:
  workflow_call:
    inputs:
      fileName:
        type: string
        required: false
        description: Docker file name
        default: docker-compose.tests.yml

      skipSonar:
        type: boolean
        required: false
        default: false
        description: Skip sonarcloud step

#
# If you wan't to use specific environment variable on your tests,
# please copy this workflow on your project instead of using it
#
env:
  TEST_AUTH0_CLIENT_ID: ${{ secrets.TEST_AUTH0_CLIENT_ID }}
  TEST_AUTH0_CLIENT_SECRET_USER: ${{ secrets.TEST_AUTH0_CLIENT_SECRET }}
  ARTIFACT_TOKEN: ${{ secrets.ARTIFACT_TOKEN }}
  AZURE_TOKEN: ${{ secrets.AZURE_TOKEN }}
  PACKAGES_GITHUB_TOKEN: ${{ secrets.PACKAGES_GITHUB_TOKEN }}
  AUTH_API_URL: ${{ secrets.AUTH_API_URL }}
  ENCRYPTION_SECRET: ${{ secrets.ENCRYPTION_SECRET }}
  # Legacy:
  AUTH0_CLIENT_ID_USER: ${{ secrets.AUTH0_CLIENT_ID_USER }}
  AUTH0_CLIENT_SECRET_USER: ${{ secrets.AUTH0_CLIENT_SECRET_USER }}
  CLIENT_ID: ${{ secrets.TEST_AUTH0_CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.TEST_AUTH0_CLIENT_SECRET }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Run docker compose tests"
        run: docker-compose --file ${{ inputs.fileName }} up --build --abort-on-container-exit

      - name: SonarCloud Scan
        if: inputs.skipSonar == false
        uses: sonarsource/sonarqube-scan-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGES_GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io

      - name: Archive code coverage results
        if: inputs.skipSonar == true
        uses: actions/upload-artifact@v3
        with:
          name: reports-e2e
          path: reports-e2e
          retention-days: 1

      - name: Stop containers
        if: always()
        run: docker-compose -f ${{ inputs.fileName }} down
